# cookstyle todo
#
Lint/AmbiguousRegexpLiteral:
  Exclude:
    - 'test/integration/service_init/serverspec/service_init_spec.rb'
    - 'test/integration/service_runit/serverspec/service_runit_spec.rb'
    - 'test/integration/service_systemd/serverspec/service_init_spec.rb'
