sudo: required
dist: trusty

# install the pre-release chef-dk.  Use chef-stable-precise to install the stable release
addons:
  apt:
    sources:
      - chef-current-trusty
    packages:
      - chefdk

# Don't `bundle install` which takes about 1.5 mins
install: echo "skip bundle install"

branches:
  only:
  - master

services: docker

env:
  matrix:
  - INSTANCE=cron-ubuntu-1204
  - INSTANCE=cron-ubuntu-1404
  - INSTANCE=cron-ubuntu-1604
  - INSTANCE=cron-centos-5
  - INSTANCE=cron-centos-6
  - INSTANCE=cron-centos-7
  - INSTANCE=config-ubuntu-1204
  - INSTANCE=config-ubuntu-1404
  - INSTANCE=config-ubuntu-1604
  - INSTANCE=config-centos-5
  - INSTANCE=config-centos-6
  - INSTANCE=config-centos-7
  - INSTANCE=delete-validation-ubuntu-1204
  - INSTANCE=delete-validation-ubuntu-1404
  - INSTANCE=delete-validation-ubuntu-1604
  - INSTANCE=delete-validation-centos-5
  - INSTANCE=delete-validation-centos-6
  - INSTANCE=delete-validation-centos-7
  - INSTANCE=service-upstart-ubuntu-1204
  - INSTANCE=service-upstart-ubuntu-1404
  - INSTANCE=service-systemd-centos-7
  - INSTANCE=service-systemd-opensuse-132
  - INSTANCE=service-systemd-fedora-latest
  - INSTANCE=service-init-ubuntu-1204
  - INSTANCE=service-init-ubuntu-1404
  - INSTANCE=service-init-centos-5
  - INSTANCE=service-init-centos-6

before_script:
  - sudo iptables -L DOCKER || ( echo "DOCKER iptables chain missing" ; sudo iptables -N DOCKER )
  - eval "$(/opt/chefdk/bin/chef shell-init bash)"
  - /opt/chefdk/embedded/bin/chef --version
  - /opt/chefdk/embedded/bin/cookstyle --version
  - /opt/chefdk/embedded/bin/foodcritic --version

script: KITCHEN_LOCAL_YAML=.kitchen.docker.yml /opt/chefdk/embedded/bin/kitchen verify ${INSTANCE}

matrix:
  include:
  - script: /opt/chefdk/embedded/bin/cookstyle
    env:  COOKSTYLE=1
  - script: /opt/chefdk/embedded/bin/foodcritic . --exclude spec -f any -P
    env:  FOODCRITIC=1
  - script: /opt/chefdk/embedded/bin/rspec
    env:  CHEFSPEC=1
